spring:
  application:
    name: habitcare

  datasource:
    url: jdbc:postgresql://localhost:5444/{POSTGRES_DB}
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
