spring:
  application:
    name: habitcare

  datasource:
    url: jdbc:postgresql://localhost:5444/habitcare
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
